export const workshopData = [
  {
    name: "Python for beginners",
    picture: "/img/python.png",
    location: "Australia, Sydney, Street 21, House 4",
    dateTime: "26 Oct, 2021 8pm",
    hours: "2 hours",
    price: 250,
    views: 200,
  },
  {
    name: "Python for beginners",
    picture: "/img/python.png",
    location: "Australia, Sydney, Street 21, House 4",
    dateTime: "26 Oct, 2021 8pm",
    hours: "2 hours",
    price: 250,
    views: 200,
  },
  {
    name: "Python for beginners",
    picture: "/img/python.png",
    location: "Australia, Sydney, Street 21, House 4",
    dateTime: "26 Oct, 2021 8pm",
    hours: "2 hours",
    price: 250,
    views: 200,
  },
  {
    name: "Python for beginners",
    picture: "/img/python.png",
    location: "Australia, Sydney, Street 21, House 4",
    dateTime: "26 Oct, 2021 8pm",
    hours: "2 hours",
    price: 250,
    views: 200,
  },
  {
    name: "Python for beginners",
    picture: "/img/python.png",
    location: "Australia, Sydney, Street 21, House 4",
    dateTime: "26 Oct, 2021 8pm",
    hours: "2 hours",
    price: 250,
    views: 200,
  },
  {
    name: "Python for beginners",
    picture: "/img/python.png",
    location: "Australia, Sydney, Street 21, House 4",
    dateTime: "26 Oct, 2021 8pm",
    hours: "2 hours",
    price: 250,
    views: 200,
  },
  {
    name: "Python for beginners",
    picture: "/img/python.png",
    location: "Australia, Sydney, Street 21, House 4",
    dateTime: "26 Oct, 2021 8pm",
    hours: "2 hours",
    price: 250,
    views: 200,
  },
  {
    name: "Python for beginners",
    picture: "/img/python.png",
    location: "Australia, Sydney, Street 21, House 4",
    dateTime: "26 Oct, 2021 8pm",
    hours: "2 hours",
    price: 250,
    views: 200,
  },
];
